#!/run/current-system/sw/bin/bash

tmux kill-session -t 0
tmux kill-session -t 1
tmux kill-session -t 2
tmux kill-session -t 3
tmux kill-session -t 4
tmux kill-session -t 5
tmux kill-session -t 6
tmux kill-session -t 7
tmux kill-session -t 8
tmux kill-session -t 9

# tmux kill-window -t :1

